### ISSUE TITLE
Clicking extension not working on linux

### ISSUE THREAD

**Issue by threeal** [Seia-Soto/chrome-discord-presence#2]
![image](https://user-images.githubusercontent.com/10202888/103135077-67a29f80-46e8-11eb-9527-ddef95c56211.png)

i do all the installation step, but when i click the extension, it does not show anything, thus i can't enable the rich presence option

**Comment by seia-soto** [comment]
Please, post all information about your operating system, so I can test it on your platform. You may wait a few seconds to load the view of the extension because the frontend library is heavy.

**Comment by threeal** [comment]
apparently i found this error on the extension console

```
DevTools failed to load SourceMap: Could not load content for chrome-extension://ccnegelmpkfjpmbpddnppgimaffninlg/scripts/libs/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

![image](https://user-images.githubusercontent.com/10202888/103135229-76d61d00-46e9-11eb-83ea-ee77e6f3ab69.png)

by the way, i use chromium 87.0.4280.88 on ubuntu 20.04 os

**Comment by seia-soto** [comment]
That's not an error related to your error. You can ignore that error. I am also tested on the same platform and got no problem opening the popup window of the extension. Can you wait for some time after clicking the icon, so that your browser can load your extension correctly?

**Comment by threeal** [comment]
you are right, it seems that the extension need some times to show the pop up. But after i click the enable rich presence, i found another error.

```
Uncaught Error: Attempting to use a disconnected port object
    at Client.<anonymous> (background.js:23)
    at Object.<anonymous> (discord.js:1)
    at Client.a.emit (discord.js:1)
    at WebSocketConnection.triggerReady (discord.js:1)
    at WebSocketConnection.checkIfReady (discord.js:1)
    at ReadyHandler.handle (discord.js:1)
    at WebSocketPacketManager.handle (discord.js:1)
    at WebSocketConnection.onPacket (discord.js:1)
    at WebSocketConnection.onMessage (discord.js:1)
(anonymous) @ background.js:23
(anonymous) @ discord.js:1
a.emit @ discord.js:1
triggerReady @ discord.js:1
checkIfReady @ discord.js:1
handle @ discord.js:1
handle @ discord.js:1
onPacket @ discord.js:1
onMessage @ discord.js:1
```

![image](https://user-images.githubusercontent.com/10202888/103135751-1d6fed00-46ed-11eb-846f-118f89b4b2c2.png)

**Comment by seia-soto** [comment]
Yes, the time I made this extension is too past to work correctly on current. I am going to start fixing it up this weekend after Christmas.

**Comment by threeal** [comment]
anyway, i think you should modify the footer template as it's the one that makes the pop up slow to load. i try to comment that part and uncomment it, and it shows faster load without the footer.

**Comment by seia-soto** [comment]
Your idea is nice but all users aren't being affected and haven't seen that case in common. I don't think it is the right time to attach that. Thank you for letting me know. I'll close this issue as I complete refactoring the code.

(Closed by mistake)

**Comment by seia-soto** [comment]
Updated 1.1.0.
